# 应用端口
server:
  port: 7901
spring:
  application:
    # 应用名称
    name: provider-user

# eureka 配置
eureka:
  instance:
    hostname: localhost   # Eureka服务端的名字
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/

logging:
  level:
    root: INFO
