server:
  port: 7001

eureka:
  instance:
    hostname: loaclhost
  client:
    register-with-eureka: false   #表示是否向注册中心注册自己
    fetch-registry: false   #false表示自己为注册中心
    service-url:      #配置客户端所交互的Eureka(监控页面)
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
